[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "0.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/Beeketing/protobuf"

[[constraint]]
  name = "github.com/Beeketing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/Beeketing/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/Beeketing/zap"
  version = "1.7.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "github.com/Beeketing/grpc-go"
  version = "1.8.0"
